# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: erc20indexer
description: ERC-20 indexer
networks:
  - id: 131313 # Odyssey (D-chain)
    rpc_config:
      url: https://testnode.dioneprotocol.com/ext/bc/D/rpc # RPC URL that will be used to subscribe to blockchain data on this network
      initial_block_interval: 10000 # Integer
      backoff_multiplicative: 0.8 # Float
      acceleration_additive: 2000 # Integer
      interval_ceiling: 10000 # Integer
      backoff_millis: 5000 # Integer
      query_timeout_millis: 20000 # Integer
    start_block: 45
    contracts:
      - name: ERC20
        address: "0x3Dcf651FD5170CA16150865137cB85bdb2ef04bA" #WDIONE
        handler: src/EventHandlers.ts
        events:
          - event: "Approval(address indexed owner, address indexed spender, uint256 value)"
          - event: "Transfer(address indexed from, address indexed to, uint256 value)"
# Rollback on reorg mode currently incurs a performance hit on historical sync
# while developing an indexer we recommend setting this to false
rollback_on_reorg: false
